### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by nikita-leonov** [z0w0/helm#118]
On MacOS for both hello & flappy examples screen is flickering as it does not "flip" screen buffer when complete render is done but does it in the middle or something. Is it a known issue? Does flickering exists on other platforms?

**Comment by nikita-leonov** [comment]
Attached a video with flickering.
[helm-refresh-bug.zip](https://github.com/z0w0/helm/files/1321957/helm-refresh-bug.zip)

**Comment by z0w0** [comment]
Doesn't happen for me on Linux, but can't say I'm surprised - the rendering flow is fairly rudimentary and unoptimized. Definitely a bug.

**Comment by nikita-leonov** [comment]
Actually I may provide misleading information. I was using helm 1.0.0 which is a year old release. Meanwhile there are other commits in master including support re-render only on change, that can affect flickering too.

**Comment by nikita-leonov** [comment]
With all the changed done on #111 I can not reproduce it anymore, I will close this issue as soon as #123  will be merged in.
