### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by nikita-leonov** [z0w0/helm#122]
@z0w0 there is an event happening through October to support open source projects. It may  bringing more eyeballs to the project so it will get more commits etc — https://hacktoberfest.digitalocean.com Can you add a hacktoberfest tag to some of the issues that are more or less ready to go, so the project will appear in a list of hackroberfest projects?

**Comment by z0w0** [comment]
@nikita-leonov I've added you as a maintainer since you've been pretty dedicated the past few days :) feel free to tag anything you see fit, otherwise I'll take a look when I get home later.
