### ISSUE TITLE
Support modular graphics engines

### ISSUE THREAD

**Issue by z0w0** [z0w0/helm#51]
The plan is to eventually have an OpenGL backed 2d renderer. But I think we should just make some sort of graphics system module out of the box. This could be extended somehow so that we could have a 2d and 3d renderer. They would all return `Element` in the long run, or perhaps a new abstract `Screen` type. This would allow us to have both a 2d cairo engine and 2d OpenGL engine in the one release, with the OpenGL one marked as experimental.

**Comment by Jefffrey** [comment]
How would functions like `isDown` find the correct overload though?

**Comment by kvanberendonck** [comment]
Problem with using a record is that every Helm call becomes indirect. You don't want that for performance: use a type class.

**Comment by z0w0** [comment]
Helm 1.0.0 added modular engines. Feel free to open a new issue if you don't think it covers it well enough.
