### ISSUE TITLE
Cairo error on rendering

### ISSUE THREAD

**Issue by Benjamin-L** [z0w0/helm#68]
The following code (taken directly from the example) fails with the error "user error (invalid value for stride)":

```
import FRP.Helm
import qualified FRP.Helm.Window as Window

render :: (Int, Int) -> Element
render (w, h) = collage w h [move (100, 100) $ filled red $ square 64]

main :: IO ()
main = do
        engine <- startup defaultConfig
        run engine $ render <~ Window.dimensions engine
```

This error does not occur when the line is changed to
```
render (w,h) = collage w h []
```

I am running Gentoo Linux with the Awesome window manager (though I don't think that the WM matters) with Cairo 0.12.5.0 and Helm 0.6.1 from hackage, tough it also fails with the latest source from git.

**Comment by z0w0** [comment]
This should be fixed in Helm 1.0.0. Feel free to reopen if it's still broken.
