### ISSUE TITLE
Build of cairo fails (osx, linux?)

### ISSUE THREAD

**Issue by maun** [z0w0/helm#87]
I am on OSX 10.10 and building cairo fails with an error very similar to this one:
http://hackage.haskell.org/package/helm-0.7.1/reports/1

Cairo and pango 0.13 do build, so I suggest updating them

**Comment by maun** [comment]
Was not so difficult after all.

**Comment by bmabsout** [comment]
confirmed same problem on linux, i am on arch and i get exit failure 1 during configuration step cairo build error

**Comment by z0w0** [comment]
Now using Cairo 0.13 and Pango 0.13
