### ISSUE TITLE
Build fails on Mint 17

### ISSUE THREAD

**Issue by pcstl** [z0w0/helm#90]
While trying to build on Mint 17 using GHC 7.8.3, the build fails with exactly the same error shown here: http://hackage.haskell.org/package/helm-0.7.1/reports/1

The error seems to come from glib 0.12.5.4. glib 0.13.0.7 builds successfully on my system, so it might be a good idea to upgrade to the newer version.

**Comment by kasbah** [comment]
We can't easily change the version of glib that cairo/pango depend on. Maybe this is an issue with your gtk2hs build tool? What is your output for `gtk2hsC2hs --version`?

**Comment by glitchG** [comment]
Output is as follows:

`C->Haskell Compiler, version 0.13.12 (gtk2hs branch) "Bin IO", 27 May 2012`

**Comment by richardblackman** [comment]
I also have a similar problem on OSX building using the guide on the helm web site.

**Comment by naphthalene** [comment]
What is the correct version of gtk2hs package from cabal?
Will installing via a stackage snapshot alleviate this issue?

Any workarounds would be welcome.
Xubuntu 14.04 LTS
libgtk2.0-common                               2.24.23-0ubuntu1.2
C->Haskell Compiler, version 0.13.12 (gtk2hs branch) "Bin IO", 27 May 2012
SDL 2.0.3 from [this PPA](https://launchpad.net/~zoogie/+archive/ubuntu/sdl2-snapshots)

**Comment by Lokidottir** [comment]
I'm also having this issue on debian sid, same failed build log.

**Comment by kasbah** [comment]
Have you tried building using stack? Last I was looking to compile I only managed via stack so I would recommend that.

**Comment by Lokidottir** [comment]
Still getting the same issues with `stack build`, Cairo & Glib failing to build from what looks like a type error ([log](http://pastebin.com/L36fnVGN)).

**Comment by Lokidottir** [comment]
Still getting the same issue, glib/cairo failing to build ([log](http://pastebin.com/7c4uEVCB))

**Comment by z0w0** [comment]
Closing this due to the rework. If it's still happening, please reopen a new issue.
